### ISSUE TITLE
Missing python package dependencies

### ISSUE THREAD

**Issue by eabase** [AVSystem/Anjay#67]
On this page: 
https://avsystem.github.io/Anjay-doc/Tools/CliLwM2MServer.html#lwm2m-testing-shell

You say:
> You can start the server (from the main Anjay directory) by running `./tests/integration/framework/nsh-lwm2m/nsh_lwm2m.py` with the following optional arguments...

However, trying that results in the missing python packages:
```bash
$ ./tests/integration/framework/nsh-lwm2m/nsh_lwm2m.py -h
Traceback (most recent call last):
  File "C:\mydev\pr_anjay\Anjay\tests\integration\framework\nsh-lwm2m\nsh_lwm2m.py", line 20, in <module>
    from lwm2m.server import Lwm2mServer
  File "C:\mydev\pr_anjay\Anjay\tests\integration\framework\lwm2m\server.py", line 11, in <module>
    from .messages import get_lwm2m_msg
  File "C:\mydev\pr_anjay\Anjay\tests\integration\framework\lwm2m\messages.py", line 19, in <module>
    from .senml_cbor import *
  File "C:\mydev\pr_anjay\Anjay\tests\integration\framework\lwm2m\senml_cbor.py", line 10, in <module>
    import cbor2
ModuleNotFoundError: No module named 'cbor2'
```

**What are the packages needed to run all your python scripts?**

**Comment by eabase** [comment]
Hi @kFYatek 

We're not using Docker, so that it's a no-go.

> then you can refer to the pip3 install line for the macOS platform

Thank you, but there must be something else missing, as I keep getting import errors.

```bash
# python.exe  nsh_lwm2m.py

Traceback (most recent call last):
  File "C:\mydev\pr_anjay\Anjay\tests\integration\framework\nsh-lwm2m\nsh_lwm2m.py", line 24, in <module>
    from cbor_shell import CBORBuilderShell
  File "C:\mydev\pr_anjay\Anjay\tests\integration\framework\nsh-lwm2m\cbor_shell.py", line 13, in <module>
    import powercmd
  File "C:\mydev\pr_anjay\Anjay\tests\integration\framework\nsh-lwm2m\powercmd\powercmd\__init__.py", line 5, in <module>
    from .cmd import Cmd
  File "C:\mydev\pr_anjay\Anjay\tests\integration\framework\nsh-lwm2m\powercmd\powercmd\cmd.py", line 42, in <module>
    from prompt_toolkit import PromptSession
ModuleNotFoundError: No module named 'prompt_toolkit'
```

**Comment by eabase** [comment]
It was missing `powercmd` which also installs  `prompt-toolkit`.

The following pip packages are needed:
```bash
pip install -U cbor2 aiocoap cryptography packaging wheel powercmd
```

Please update your requirements & documentation!
